# Generated by Django 2.0.3 on 2018-03-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_short_description',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
